-- vim.pack.add({
--   "folke/lazydev.nvim",
-- })
--
-- require("lazydev").setup({
--   library = {
--     -- See the docs for more details
--     -- Load luvit types when the `vim.uv` word is found
--     { path = "${3rd}/luv/library", words = { "vim%.uv" } },
--   },
-- })
